version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...==========================================
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 093272453328.dkr.ecr.ap-northeast-2.amazonaws.com
      - aws eks --region ap-northeast-2 update-kubeconfig --name newdeal
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Started build phase..
      - mvn clean package
      - echo Building the Docker image...
      - docker build -t newdeal-security .
      - docker tag newdeal-security:latest 093272453328.dkr.ecr.ap-northeast-2.amazonaws.com/newdeal-security:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo Image_Version - $CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push 093272453328.dkr.ecr.ap-northeast-2.amazonaws.com/newdeal-security:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo List directory
      - ls -la
      - echo Push the latest image to cluster
      - REPOSITORY_URI=093272453328.dkr.ecr.ap-northeast-2.amazonaws.com/newdeal-security
      - sed -i 's@CONTAINER_IMAGE_TAG@'"$REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION"'@' k8s-deploy.yaml
      - DB_URL=${NEWDEAL_DATASOURCE_HOST}
      - sed -i 's@NEWDEAL_DATASOURCE_HOST_TAG@'"$DB_URL"'@' k8s-deploy.yaml
      - DB_URL=${NEWDEAL_DATASOURCE_PORT}
      - sed -i 's@NEWDEAL_DATASOURCE_PORT_TAG@'"$DB_URL"'@' k8s-deploy.yaml
      - DB_URL=${NEWDEAL_DATASOURCE_DBNAME}
      - sed -i 's@NEWDEAL_DATASOURCE_DBNAME_TAG@'"$DB_URL"'@' k8s-deploy.yaml
      - DB_URL=${NEWDEAL_DATASOURCE_USERNAME}
      - sed -i 's@NEWDEAL_DATASOURCE_USERNAME_TAG@'"$DB_URL"'@' k8s-deploy.yaml
      - DB_URL=${NEWDEAL_DATASOURCE_PASSWORD}
      - sed -i 's@NEWDEAL_DATASOURCE_PASSWORD_TAG@'"$DB_URL"'@' k8s-deploy.yaml
      - DB_URL=${NEWDEAL_API_FRONT_URL}
      - sed -i 's@NEWDEAL_API_FRONT_URL_TAG@'"$DB_URL"'@' k8s-deploy.yaml
      - DB_URL=${NEWDEAL_API_SECURITY_URL}
      - sed -i 's@NEWDEAL_API_SECURITY_URL_TAG@'"$DB_URL"'@' k8s-deploy.yaml
      - DB_URL=${NEWDEAL_API_BACKEND_URL}
      - sed -i 's@NEWDEAL_API_BACKEND_URL_TAG@'"$DB_URL"'@' k8s-deploy.yaml
      - kubectl apply -f k8s-deploy.yaml
